### ISSUE TITLE
本地入参方式选定后，入参该怎么传呢？

### ISSUE THREAD

**Issue by anZong** [TencentCloud/scf-node-debug#3]

**Comment by anZong** [comment]
event的参数，我现在是在函数入口处固定了参数值

**Comment by Lighting-Jack** [comment]
在本地的3000端口（默认）启动云函数调试工具（scf-cli）后，可借助curl或者postMan模拟发送请求，如果你想动态地从urlParams/post-body/form-data/请求头header等位置传入参数时，请选择入参方式为http，然后在云函数中即可从event对象中读取到你刚刚传入的参数值。
